This is makeindex, version 2.16 [MiKTeX 23.5].
Scanning style file ./utfprct.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file utfprct.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file utfprct.acr....done (6 lines written, 0 warnings).
Output written in utfprct.acr.
Transcript written in utfprct.alg.
